import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "ru" | "en" | "kk";

export const LANGUAGES: { code: Lang; label: string; flag: string }[] = [
  { code: "kk", label: "KK", flag: "🇰🇿" },
  { code: "en", label: "EN", flag: "🇬🇧" },
  { code: "ru", label: "RU", flag: "🇷🇺" },
];

// ─────────────────────────────────────────────────────────────────────────────
// Translations
// ─────────────────────────────────────────────────────────────────────────────

const translations = {
  ru: {
    appName: "FIN-NEST",
    appSubtitle: "Семейные финансы",
    loading: "Загрузка...",
    allFamily: "Вся семья",
    or: "или",
    logout: "Выйти",
    dateAtFormat: "dd MMM yyyy 'в' HH:mm",

    profileSelector: {
      title: "Кто вы?",
      subtitle: "Выберите ваш профиль из членов семьи",
      continue: "Продолжить",
      selectProfile: "Выберите профиль",
      switchProfile: "Сменить профиль",
      currentProfile: "Текущий профиль",
      switchProfileTitle: "Сменить профиль",
      switchProfileDesc: "Выберите другого члена семьи",
      profileChanged: "Профиль изменен",
      enterPin: "Введите PIN-код",
      enterPinFor: "Введите PIN-код для",
      wrongPin: "Неверный PIN-код",
      pinRequired: "Требуется PIN-код",
    },

    auth: {
      welcome: "Добро пожаловать!",
      signInSubtitle: "Войдите в семейный аккаунт",
      email: "Email",
      emailPlaceholder: "family@example.com",
      password: "Пароль",
      passwordPlaceholder: "••••••••",
      forgotPassword: "Забыли пароль?",
      signIn: "Войти",
      signingIn: "Вход...",
      noAccount: "Нет аккаунта?",
      register: "Зарегистрироваться",
      signInWithGoogle: "Войти через Google",
      redirecting: "Перенаправление...",
      createAccount: "Создать аккаунт",
      oneAccountSubtitle: "Один аккаунт для всей семьи",
      familyOwnerName: "Имя семьи / Владелец",
      namePlaceholder: "Семья ақпантоқпантұрарқожа",
      confirmPassword: "Подтвердить пароль",
      confirmPasswordPlaceholder: "Повторите пароль",
      registerButton: "Зарегистрироваться",
      registering: "Создание аккаунта...",
      alreadyHaveAccount: "Уже есть аккаунт?",
      signInLink: "Войти",
      registerWithGoogle: "Регистрация через Google",
      passwordStrengthWeak: "Слабый",
      passwordStrengthMedium: "Средний",
      passwordStrengthGood: "Хороший",
      passwordStrengthStrong: "Сильный",
      forgotTitle: "Восстановление пароля",
      forgotSubtitle: "Введите email аккаунта и мы вышлем ссылку для сброса пароля",
      sendLink: "Отправить ссылку",
      sending: "Отправка...",
      emailSentTitle: "Письмо отправлено!",
      emailSentSubtitle: "Мы отправили ссылку для сброса пароля на",
      checkSpam: "Проверьте папку «Спам», если письмо не пришло.",
      backToLogin: "Вернуться ко входу",
      newPasswordTitle: "Новый пароль",
      newPasswordSubtitle: "Придумайте надёжный пароль для вашего семейного аккаунта",
      checkingLink: "Проверяем ссылку для сброса...",
      savePassword: "Сохранить пароль",
      saving: "Сохранение...",
      passwordUpdatedTitle: "Пароль обновлён!",
      passwordUpdatedSubtitle: "Перенаправляем вас в приложение...",
      minPasswordLength: "Пароль должен содержать минимум 6 символов.",
      passwordsDoNotMatch: "Пароли не совпадают.",
      invalidCredentials: "Неверный email или пароль. Попробуйте снова.",
      googleError: "Ошибка входа через Google: ",
      googleProviderDisabled: "Google OAuth не настроен в Supabase. Перейдите в Dashboard → Authentication → Providers → Google и включите его.",
      registrationError: "Ошибка регистрации. Попробуйте снова.",
      connectionError: "Ошибка соединения. Попробуйте снова.",
      accountCreated: "Аккаунт создан! Теперь войдите.",
      resetEmailError: "Не удалось отправить письмо. Проверьте email и попробуйте снова.",
      resetPasswordError: "Ошибка обновления пароля. Попробуйте получить новую ссылку.",
    },

    nav: {
      home: "Главная",
      add: "Добавить",
      history: "История",
      budgets: "Бюджеты",
      family: "Семья",
    },

    dashboard: {
      balance: "Балас",
      totalBalance: "Общий баланс",
      positiveBalance: "Положительный баланс",
      negativeBalance: "Отрицательный баланс",
      income: "Доходы",
      expenses: "Расходы",
      transactionShort: "тр.",
      byFamilyMembers: "По членам семьи",
      expenseCategories: "Категории расходов",
      incomeCategories: "Категории доходов",
      noTransactions: "Нет транзакций",
      noTransactionsHint: "Начните с добавления первой транзакции",
    },

    addTransaction: {
      title: "Добавить транзакцию",
      familyMember: "Член семьи",
      type: "Тип",
      expense: "Расход",
      income: "Доход",
      amount: "Сумма",
      category: "Категория",
      selectCategory: "Выберите категорию",
      description: "Описание",
      descriptionPlaceholder: "Введите описание",
      addButton: "Добавить транзакцию",
      fillAllFields: "Заполните все поля",
      selectMember: "Выберите члена семьи",
      invalidAmount: "Введите корректную сумму",
      incomeAdded: "Доход добавлен",
      expenseAdded: "Расход добавлен",
      noMembersTitle: "Сначала добавьте членов семьи",
      noMembersHint: "Перейдите на вкладку \"Семья\"",
    },

    transactionList: {
      filters: "Фильтры",
      type: "Тип",
      sort: "Сортировка",
      all: "Все",
      incomes: "Доходы",
      expenses: "Расходы",
      date: "Дата",
      amount: "Сумма",
      notFound: "Транзакции не найдены",
      deleted: "Транзакция удалена",
    },

    budgetManagement: {
      title: "Бюджеты",
      add: "Добавить",
      editBudget: "Редактировать бюджет",
      addBudget: "Добавить бюджет",
      editBudgetDesc: "Измените лимит бюджета",
      addBudgetDesc: "Добавьте новый лимит бюджета",
      category: "Категория",
      selectCategory: "Выберите категорию",
      monthlyLimit: "Месячный лимит",
      update: "Обновить",
      noBudgets: "Нет установленных бюджетов",
      noBudgetsHint: "Создайте бюджеты для отслеживания расходов",
      spent: "потрачено",
      of: "из",
      used: "% использовано",
      remaining: "осталось",
      overBudget: "превышение",
      budgetUpdated: "Бюджет обновлен",
      budgetAdded: "Бюджет добавлен",
      budgetDeleted: "Бюджет удален",
      fillAllFields: "Заполните все поля",
      invalidLimit: "Введите корректный лимит",
      // Bank management
      banksTitle: "Банки и карты",
      addBank: "Добавить банк",
      editBank: "Редактировать банк",
      addBankDesc: "Добавьте банковскую карту",
      editBankDesc: "Измените данные банка",
      bankName: "Название банка",
      bankNamePlaceholder: "Kaspi, Halyk, Forte и др.",
      cardNumber: "Номер карты",
      cardNumberPlaceholder: "Последние 4 цифры",
      cardBalance: "Баланс на карте",
      noBanks: "Нет добавленных банков",
      noBanksHint: "Добавьте банковские карты для отслеживания",
      bankAdded: "Банк добавлен",
      bankUpdated: "Банк обновлен",
      bankDeleted: "Банк удален",
      totalOnCards: "Всего на картах",
      addLoan: "Добавить кредит/рассрочку",
      editLoan: "Редактировать кредит",
      addLoanDesc: "Добавьте информацию о кредите или рассрочке",
      editLoanDesc: "Измените данные кредита",
      loanType: "Тип",
      credit: "Кредит",
      installment: "Рассрочка",
      loanDescription: "Описание",
      loanDescriptionPlaceholder: "Например: iPhone 15 Pro",
      totalAmount: "Общая сумма",
      remainingAmount: "Остаток долга",
      monthlyPayment: "Ежемесячный платёж",
      loans: "Кредиты и рассрочки",
      noLoans: "Нет кредитов",
      loanAdded: "Кредит добавлен",
      loanUpdated: "Кредит обновлен",
      loanDeleted: "Кредит удаен",
      debtRemaining: "долга осталось",
      perMonth: "в месяц",
    },

    familyManagement: {
      title: "Отбасы мүшелері",
      add: "Қосу",
      editMember: "Отбасы мүшесін өңдеу",
      addMember: "Отбасы мүшесін қосу",
      editMemberDesc: "Отбасы мүшесінің деректерін өзгертіңіз",
      addMemberDesc: "Жаңа отбасы мүшесін қосыңыз",
      name: "Аты",
      namePlaceholder: "Атын енгізіңіз",
      color: "Түсі",
      pin: "PIN (4 сан)",
      pinPlaceholder: "Талап емес",
      pinOptional: "Талап емес",
      pinInvalid: "PIN 4 санды түрде болуы керек",
      update: "Жаңарту",
      noMembers: "Отбасы мүшелері жоқ",
      noMembersHint: "Қадағалау үшін отбасы мүшелерін қосыңыз",
      memberUpdated: "Отбасы мүшесі жаңартылды",
      memberAdded: "Отбасы мүшесі қосылды",
      atLeastOne: "Кемінде бір отбасы мүшесі болуы тиіс",
      memberDeleted: "Отбасы мүшесі жойылды",
      enterName: "Отбасы мүшесінің атын енгізіңіз",
    },

    settings: {
      title: "Баптаулар",
      language: "Тіл",
      notifications: "Хабарламалар",
      security: "Қауіпсіздік",
      help: "Көмек",
      about: "Қолданба туралы",
      version: "Нұсқа",
      contact: "Бізбен хабарласу",
      privacy: "Құпиялылық",
      terms: "Қолдану шарттары",
      backup: "Резервтік көшірмелеу",
      restore: "Деректерді қалпына келтіру",
      clearData: "Барлық деректерді тазалау",
      export: "Деректерді экспорттау",
      import: "Деректерді импорттау",
    },

    categories: {
      "Зарплата": "Зарплата",
      "Фриланс": "Фриланс",
      "Инвестиции": "Инвестиции",
      "Подарок": "Подарок",
      "Другой доход": "Другой доход",
      "Продукты": "Продукты",
      "Транспорт": "Транспорт",
      "Коммунальные услуги": "Коммунальные услуги",
      "Развлечения": "Развлечения",
      "Здоровье": "Здоровье",
      "Образование": "Образование",
      "Покупки": "Покупки",
      "Рестораны": "Рестораны",
      "Другие расходы": "Другие расходы",
    },
  },

  en: {
    appName: "FIN-NEST",
    appSubtitle: "Family Finances",
    loading: "Loading...",
    allFamily: "All Family",
    or: "or",
    logout: "Sign Out",
    dateAtFormat: "dd MMM yyyy 'at' HH:mm",

    profileSelector: {
      title: "Who are you?",
      subtitle: "Select your profile from family members",
      continue: "Continue",
      selectProfile: "Select profile",
      switchProfile: "Switch profile",
      currentProfile: "Current profile",
      switchProfileTitle: "Switch profile",
      switchProfileDesc: "Select another family member",
      profileChanged: "Profile changed",
      enterPin: "Enter PIN code",
      enterPinFor: "Enter PIN code for",
      wrongPin: "Wrong PIN code",
      pinRequired: "PIN code required",
    },

    auth: {
      welcome: "Welcome back!",
      signInSubtitle: "Sign in to your family account",
      email: "Email",
      emailPlaceholder: "family@example.com",
      password: "Password",
      passwordPlaceholder: "••••••••",
      forgotPassword: "Forgot password?",
      signIn: "Sign In",
      signingIn: "Signing in...",
      noAccount: "No account?",
      register: "Register",
      signInWithGoogle: "Sign in with Google",
      redirecting: "Redirecting...",
      createAccount: "Create Account",
      oneAccountSubtitle: "One account for the whole family",
      familyOwnerName: "Family Name / Owner",
      namePlaceholder: "The Akpantokpanturarkozha Family",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Repeat password",
      registerButton: "Register",
      registering: "Creating account...",
      alreadyHaveAccount: "Already have an account?",
      signInLink: "Sign In",
      registerWithGoogle: "Register with Google",
      passwordStrengthWeak: "Weak",
      passwordStrengthMedium: "Medium",
      passwordStrengthGood: "Good",
      passwordStrengthStrong: "Strong",
      forgotTitle: "Password Recovery",
      forgotSubtitle: "Enter your account email and we'll send a password reset link",
      sendLink: "Send Link",
      sending: "Sending...",
      emailSentTitle: "Email Sent!",
      emailSentSubtitle: "We sent a password reset link to",
      checkSpam: "Check your Spam folder if the email didn't arrive.",
      backToLogin: "Back to login",
      newPasswordTitle: "New Password",
      newPasswordSubtitle: "Create a secure password for your family account",
      checkingLink: "Verifying reset link...",
      savePassword: "Save Password",
      saving: "Saving...",
      passwordUpdatedTitle: "Password Updated!",
      passwordUpdatedSubtitle: "Redirecting you to the app...",
      minPasswordLength: "Password must be at least 6 characters.",
      passwordsDoNotMatch: "Passwords do not match.",
      invalidCredentials: "Invalid email or password. Please try again.",
      googleError: "Google sign-in error: ",
      googleProviderDisabled: "Google OAuth is not configured in Supabase. Go to Dashboard → Authentication → Providers → Google and enable it.",
      registrationError: "Registration error. Please try again.",
      connectionError: "Connection error. Please try again.",
      accountCreated: "Account created! Please sign in.",
      resetEmailError: "Failed to send email. Check your email and try again.",
      resetPasswordError: "Password update failed. Try requesting a new link.",
    },

    nav: {
      home: "Home",
      add: "Add",
      history: "History",
      budgets: "Budgets",
      family: "Family",
    },

    dashboard: {
      balance: "Balance",
      totalBalance: "Total Balance",
      positiveBalance: "Positive balance",
      negativeBalance: "Negative balance",
      income: "Income",
      expenses: "Expenses",
      transactionShort: "tr.",
      byFamilyMembers: "By Family Member",
      expenseCategories: "Expense Categories",
      incomeCategories: "Income Categories",
      noTransactions: "No transactions",
      noTransactionsHint: "Start by adding your first transaction",
    },

    addTransaction: {
      title: "Add Transaction",
      familyMember: "Family Member",
      type: "Type",
      expense: "Expense",
      income: "Income",
      amount: "Amount",
      category: "Category",
      selectCategory: "Select category",
      description: "Description",
      descriptionPlaceholder: "Enter description",
      addButton: "Add Transaction",
      fillAllFields: "Please fill in all fields",
      selectMember: "Please select a family member",
      invalidAmount: "Please enter a valid amount",
      incomeAdded: "Income added",
      expenseAdded: "Expense added",
      noMembersTitle: "Add family members first",
      noMembersHint: "Go to the \"Family\" tab",
    },

    transactionList: {
      filters: "Filters",
      type: "Type",
      sort: "Sort",
      all: "All",
      incomes: "Income",
      expenses: "Expenses",
      date: "Date",
      amount: "Amount",
      notFound: "No transactions found",
      deleted: "Transaction deleted",
    },

    budgetManagement: {
      title: "Budgets",
      add: "Add",
      editBudget: "Edit Budget",
      addBudget: "Add Budget",
      editBudgetDesc: "Change the budget limit",
      addBudgetDesc: "Add a new budget limit",
      category: "Category",
      selectCategory: "Select category",
      monthlyLimit: "Monthly Limit",
      update: "Update",
      noBudgets: "No budgets set",
      noBudgetsHint: "Create budgets to track your expenses",
      spent: "spent",
      of: "of",
      used: "% used",
      remaining: "remaining",
      overBudget: "over budget",
      budgetUpdated: "Budget updated",
      budgetAdded: "Budget added",
      budgetDeleted: "Budget deleted",
      fillAllFields: "Please fill in all fields",
      invalidLimit: "Please enter a valid budget limit",
      // Bank management
      banksTitle: "Banks & Cards",
      addBank: "Add Bank",
      editBank: "Edit Bank",
      addBankDesc: "Add a bank card",
      editBankDesc: "Edit bank details",
      bankName: "Bank Name",
      bankNamePlaceholder: "Kaspi, Halyk, Forte, etc.",
      cardNumber: "Card Number",
      cardNumberPlaceholder: "Last 4 digits",
      cardBalance: "Card Balance",
      noBanks: "No banks added",
      noBanksHint: "Add bank cards for tracking",
      bankAdded: "Bank added",
      bankUpdated: "Bank updated",
      bankDeleted: "Bank deleted",
      totalOnCards: "Total on Cards",
      addLoan: "Add Credit/Installment",
      editLoan: "Edit Credit",
      addLoanDesc: "Add credit or installment information",
      editLoanDesc: "Edit credit details",
      loanType: "Type",
      credit: "Credit",
      installment: "Installment",
      loanDescription: "Description",
      loanDescriptionPlaceholder: "e.g., iPhone 15 Pro",
      totalAmount: "Total Amount",
      remainingAmount: "Remaining Debt",
      monthlyPayment: "Monthly Payment",
      loans: "Credits & Installments",
      noLoans: "No credits",
      loanAdded: "Credit added",
      loanUpdated: "Credit updated",
      loanDeleted: "Credit deleted",
      debtRemaining: "debt remaining",
      perMonth: "per month",
    },

    familyManagement: {
      title: "Family Members",
      add: "Add",
      editMember: "Edit Family Member",
      addMember: "Add Family Member",
      editMemberDesc: "Change family member details",
      addMemberDesc: "Add a new family member",
      name: "Name",
      namePlaceholder: "Enter name",
      color: "Color",
      pin: "PIN (4 digits)",
      pinPlaceholder: "Optional",
      pinOptional: "Optional",
      pinInvalid: "PIN must be 4 digits",
      update: "Update",
      noMembers: "No family members",
      noMembersHint: "Add family members to start tracking",
      memberUpdated: "Family member updated",
      memberAdded: "Family member added",
      atLeastOne: "Must have at least one family member",
      memberDeleted: "Family member deleted",
      enterName: "Please enter a name",
    },

    settings: {
      title: "Settings",
      language: "Language",
      notifications: "Notifications",
      security: "Security",
      help: "Help",
      about: "About the app",
      version: "Version",
      contact: "Contact us",
      privacy: "Privacy",
      terms: "Terms of use",
      backup: "Backup",
      restore: "Restore data",
      clearData: "Clear all data",
      export: "Export data",
      import: "Import data",
    },

    categories: {
      "Зарплата": "Salary",
      "Фриланс": "Freelance",
      "Инвестиции": "Investments",
      "Подарок": "Gift",
      "Другой доход": "Other Income",
      "Продукты": "Groceries",
      "Транспорт": "Transport",
      "Коммунальные услуги": "Utilities",
      "Развлечения": "Entertainment",
      "Здоровье": "Health",
      "Образование": "Education",
      "Покупки": "Shopping",
      "Рестораны": "Restaurants",
      "Другие расходы": "Other Expenses",
    },
  },

  kk: {
    appName: "FIN-NEST",
    appSubtitle: "Отбасылық қаржы",
    loading: "Жүктелуде...",
    allFamily: "Барлық отбасы",
    or: "немесе",
    logout: "Шығу",
    dateAtFormat: "dd MMM yyyy HH:mm",

    profileSelector: {
      title: "Сіз кімсіз?",
      subtitle: "От��асы мүшелерінен профиліңізді таңдаңыз",
      continue: "Жалғастыру",
      selectProfile: "Профилі таңдау",
      switchProfile: "Профилін ауыстыру",
      currentProfile: "Ағымдағы профилі",
      switchProfileTitle: "Профилін ауыстыру",
      switchProfileDesc: "Басқа бір отбасы мүшесін таңдаңыз",
      profileChanged: "Профилі өзгертілді",
      enterPin: "PIN кодын енгізіңіз",
      enterPinFor: "PIN кодын енгізіңіз",
      wrongPin: "Қате PIN коды",
      pinRequired: "PIN коды талап етіледі",
    },

    auth: {
      welcome: "Қош келдіңіз!",
      signInSubtitle: "Отбасылық аккаунтқа кіріңіз",
      email: "Email",
      emailPlaceholder: "family@example.com",
      password: "Құпия сөз",
      passwordPlaceholder: "••••••••",
      forgotPassword: "Құпия сөзді ұмыттыңыз ба?",
      signIn: "Кіру",
      signingIn: "Кіруде...",
      noAccount: "Аккаунт жоқ па?",
      register: "Тіркелу",
      signInWithGoogle: "Google арқылы кіру",
      redirecting: "Бағыттауда...",
      createAccount: "Аккаунт жасау",
      oneAccountSubtitle: "Бүкіл отбасы үшін бір аккаунт",
      familyOwnerName: "Отбасы аты / Иесі",
      namePlaceholder: "Ақпантоқпантұрарқожа отбасы",
      confirmPassword: "Құпия сөзді растау",
      confirmPasswordPlaceholder: "Құпия сөзді қайталаңыз",
      registerButton: "Тіркелу",
      registering: "Аккаунт жасалуда...",
      alreadyHaveAccount: "Аккаунт бар ма?",
      signInLink: "Кіру",
      registerWithGoogle: "Google арқылы тіркелу",
      passwordStrengthWeak: "Әлсіз",
      passwordStrengthMedium: "Орташа",
      passwordStrengthGood: "Жақсы",
      passwordStrengthStrong: "Күшті",
      forgotTitle: "Құпия сөзді қалпына келтіру",
      forgotSubtitle: "Аккаунт email-ін енгізіңіз, біз сілтеме жібереміз",
      sendLink: "Сілтеме жіберу",
      sending: "Жіберілуде...",
      emailSentTitle: "Хат жіберілді!",
      emailSentSubtitle: "Біз құпия сөзді қалпына келтіру сілтемесін жібердік",
      checkSpam: "Хат келмесе «Спам» қалтасын тексеріңіз.",
      backToLogin: "Кіруге оралу",
      newPasswordTitle: "Жаңа құпия сөз",
      newPasswordSubtitle: "Отбасылық аккаунтыңыз үшін сенімді құпия сөз ойлап табыңыз",
      checkingLink: "Қалпына келтіру сілтемесі тексерілуде...",
      savePassword: "Құпия сөзді сақтау",
      saving: "Сақталуда...",
      passwordUpdatedTitle: "Құпия сөз жаңартылды!",
      passwordUpdatedSubtitle: "Қолданбаға бағыттаудамыз...",
      minPasswordLength: "Құпия сөз кемінде 6 таңбадан тұруы тиіс.",
      passwordsDoNotMatch: "Құпия сөздер сәйкес келмейді.",
      invalidCredentials: "Қате email немесе құпия сөз. Қайталап көріңіз.",
      googleError: "Google кіру қатесі: ",
      googleProviderDisabled: "Google OAuth Supabase-де баптанбаған. Dashboard → Authentication → Providers → Google бөліміне өтіп қосыңыз.",
      registrationError: "Тіркелу қатесі. Қайталап көріңіз.",
      connectionError: "Байланыс қатесі. Қайталап көріңіз.",
      accountCreated: "Аккаунт жасалды! Енді кіріңіз.",
      resetEmailError: "Хат жіберілмеді. Email-ді тексеріп, қайталап көріңіз.",
      resetPasswordError: "Құпия сөзді жаңарту сәтсіз болды. Жаңа сілтеме сұраңыз.",
    },

    nav: {
      home: "Басты",
      add: "Қосу",
      history: "Тарих",
      budgets: "Бюджеттер",
      family: "Отбасы",
    },

    dashboard: {
      balance: "Баланс",
      totalBalance: "Жалпы баланс",
      positiveBalance: "Оң баланс",
      negativeBalance: "Теріс баланс",
      income: "Кірістер",
      expenses: "Шығыстар",
      transactionShort: "мәм.",
      byFamilyMembers: "Отбасы мүшелері бойынша",
      expenseCategories: "Шығыс санаттары",
      incomeCategories: "Кіріс санаттары",
      noTransactions: "Транзакциялар жоқ",
      noTransactionsHint: "Бірінші транзакцияны қосудан бастаңыз",
    },

    addTransaction: {
      title: "Транзакция қосу",
      familyMember: "Отбасы мүшесі",
      type: "Түрі",
      expense: "Шығыс",
      income: "Кіріс",
      amount: "Сома",
      category: "Санат",
      selectCategory: "Санатты таңдаңыз",
      description: "Сипаттама",
      descriptionPlaceholder: "Сипаттаманы енгізіңіз",
      addButton: "Транзакция қосу",
      fillAllFields: "Барлық өрістерді толтырыңыз",
      selectMember: "Отбасы мүшесін таңдаңыз",
      invalidAmount: "Дұрыс соманы енгізіңіз",
      incomeAdded: "Кіріс қосылды",
      expenseAdded: "Шығыс қослды",
      noMembersTitle: "Алдымен отбасы мүшелерін қосыңыз",
      noMembersHint: "«Отбасы» қойындысына өтіңіз",
    },

    transactionList: {
      filters: "Сүзгілер",
      type: "Түрі",
      sort: "Сұрыптау",
      all: "Барлығы",
      incomes: "Кірістер",
      expenses: "Шығыстар",
      date: "Күні",
      amount: "Сома",
      notFound: "Транзакциялар табылмады",
      deleted: "Транзакция жойылды",
    },

    budgetManagement: {
      title: "Бюджеттер",
      add: "Қосу",
      editBudget: "Бюджетті өңдеу",
      addBudget: "Бюджет қосу",
      editBudgetDesc: "Бюджет лимитін өзгертіңіз",
      addBudgetDesc: "Жаңа бюджет лимитін қосыңыз",
      category: "Санат",
      selectCategory: "Санатты таңдаңыз",
      monthlyLimit: "Айлық лимит",
      update: "Жаңарту",
      noBudgets: "Белгіленген бюджеттер жоқ",
      noBudgetsHint: "Шығыстарды қадағалау үшін бюджеттер жасаңыз",
      spent: "жұмсалды",
      of: "ішінен",
      used: "% пайдаланылды",
      remaining: "қалды",
      overBudget: "асып кету",
      budgetUpdated: "Бюджет жаңартылды",
      budgetAdded: "Бюджет қосылды",
      budgetDeleted: "Бюджет жойылды",
      fillAllFields: "Барлық өрістерді толтырыңыз",
      invalidLimit: "Дұрыс лимитті енгізңіз",
      // Bank management
      banksTitle: "Банки және карталар",
      addBank: "Банк қосу",
      editBank: "Банкты өңдеу",
      addBankDesc: "Банк картасын қосу",
      editBankDesc: "Банк маалыматын өңдеу",
      bankName: "Банк аты",
      bankNamePlaceholder: "Kaspi, Halyk, Forte және т.б.",
      cardNumber: "Карта нөмірі",
      cardNumberPlaceholder: "Соңғы 4 санды",
      cardBalance: "Карта балансы",
      noBanks: "Банктар қосылған жок",
      noBanksHint: "Қадағалау үшін банк карталарын қосыңыз",
      bankAdded: "Банк қосылды",
      bankUpdated: "Банк жаңартылды",
      bankDeleted: "Банк жойылды",
      totalOnCards: "Каралардағы жалпы сома",
      addLoan: "Кредит/қарыз қосу",
      editLoan: "Кредитті өңдеу",
      addLoanDesc: "Кредит немесе қарыз маалыматын қосу",
      editLoanDesc: "Кредит маалыматын өңдеу",
      loanType: "Түрі",
      credit: "Кредит",
      installment: "Қарыз",
      loanDescription: "Сипаттама",
      loanDescriptionPlaceholder: "Мисалы: iPhone 15 Pro",
      totalAmount: "Жалпы сома",
      remainingAmount: "Қалған қарыз",
      monthlyPayment: "Айлық төлем",
      loans: "Кредиттер және қарыздар",
      noLoans: "Кредиттер жок",
      loanAdded: "Кредит қосылды",
      loanUpdated: "Кредит жаңартылды",
      loanDeleted: "Кредит жойылды",
      debtRemaining: "қалған қарыз",
      perMonth: "айлық",
    },

    familyManagement: {
      title: "Отбасы мүшелері",
      add: "Қосу",
      editMember: "Отбасы мүшесін өңдеу",
      addMember: "Отбасы мүшесін қосу",
      editMemberDesc: "Отбасы мүшесінің деректерін өзгертіңіз",
      addMemberDesc: "Жаңа отбасы мүшесін қосыңыз",
      name: "Аты",
      namePlaceholder: "Атын енгізіңіз",
      color: "Түсі",
      pin: "PIN (4 сан)",
      pinPlaceholder: "Талап емес",
      pinOptional: "Талап емес",
      pinInvalid: "PIN 4 санды түрде болуы керек",
      update: "Жаңарту",
      noMembers: "Отбасы мүшелері жоқ",
      noMembersHint: "Қадағалау үшін отбасы мүшелерін қосыңыз",
      memberUpdated: "Отбасы мүшесі жаңартылды",
      memberAdded: "Отбасы мүшесі қосылды",
      atLeastOne: "Кемінде бір отбасы мүшесі болуы тиіс",
      memberDeleted: "Отбасы мүшесі жойылды",
      enterName: "Отбасы мүшесінің атын енгізіңіз",
    },

    settings: {
      title: "Баптаулар",
      language: "Тіл",
      notifications: "Хабарламалар",
      security: "Қауіпсіздік",
      help: "Көмек",
      about: "Қолданба туралы",
      version: "Нұсқа",
      contact: "Бізбен хабарласу",
      privacy: "Құпиялылық",
      terms: "Қолдану шарттары",
      backup: "Резервтік көшірмелеу",
      restore: "Деректерді қалпына келтіру",
      clearData: "Барлық деректерді тазалау",
      export: "Деректерді экспорттау",
      import: "Деректерді импорттау",
    },

    categories: {
      "Зарплата": "Жалақы",
      "Фриланс": "Фриланс",
      "Инвестиции": "Инвестициялар",
      "Подарок": "Сыйлық",
      "Другой доход": "Басқа кіріс",
      "Продукты": "Азық-түлік",
      "Транспорт": "Көлік",
      "Коммунальные услуги": "Коммуна��дық қызметтер",
      "Развлечения": "Ойын-сауық",
      "Здоровье": "Денсаулық",
      "Образование": "Білім",
      "Покупки": "Сатып алулар",
      "Рестораны": "Мейрамханалар",
      "Другие расходы": "Басқа шығыстар",
    },
  },
} as const;

export type Translations = typeof translations.ru;

// ─────────────────────────────────────────────────────────────────────────────
// Context
// ─────────────────────────────────────────────────────────────────────────────

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
  translateCategory: (ruKey: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ru",
  setLang: () => {},
  t: translations.ru,
  translateCategory: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("finnest_lang");
    return (saved as Lang) || "ru";
  });

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("finnest_lang", newLang);
  };

  const t = translations[lang] as Translations;

  const translateCategory = (ruKey: string): string => {
    const cats = translations[lang].categories as Record<string, string>;
    return cats[ruKey] ?? ruKey;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, translateCategory }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}